x=rnorm(1,10,15)
mu=rnorm(1,10,3)
sigma=rnorm(1,15,2)
test_that("erf_dnorm works", {
  expect_true(erf_dnorm(x=x,mu=mu,sigma=sigma)>=0)
  expect_true(erf_dnorm(x=x,mu=mu,sigma=sigma)<=1)
  expect_error(erf_dnorm(x='a',mu=mu,sigma=sigma), 'All of the arguments must be numeric')
  expect_error(erf_dnorm(x=x,mu='mu',sigma=sigma), 'All of the arguments must be numeric')
  expect_error(erf_dnorm(x=x,mu=mu,sigma='sigma'), 'All of the arguments must be numeric')
  expect_error(erf_dnorm(x=x,mu=c(mu,mu),sigma=sigma), 'All of the parameters must be scalars')
  expect_error(erf_dnorm(x=x,mu=mu,sigma=c(mu,sigma)), 'All of the parameters must be scalars')
  #integrate(erf_dnorm, -Inf,Inf)
})
